version: '3.7'

services:
  ts-node:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: ts-node
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: npm run dev
  mysql:
    image: mysql:5.7
    command: [
      --character-set-server=utf8,
      --innodb-strict-mode=0,
      --innodb-file-format=barracuda,
      --innodb-file-per-table=1,
      --innodb-large-prefix=1
    ]
    restart: always
    container_name: ts-node-mysql
    ports:
      - 33060:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
